import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  projectsSidebar: [
    'intro',
    {type: 'autogenerated', dirName: 'Leatherworking'},
    {type: 'autogenerated', dirName: 'Metalworking'},
  ],
  resourcesSidebar: [{type: 'autogenerated', dirName: 'Resources'}],
};

export default sidebars;
