import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  projectsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Metalworking',
      collapsed: true,
      items: [
        'metalworking/intro',
        {
          type: 'category',
          label: 'Blacksmithing workshop',
          collapsed: true,
          items: [
            'metalworking/blacksmithing/intro',
            'metalworking/blacksmithing/first-session',
            'metalworking/blacksmithing/second-session',
          ],
        },
        {
          type: 'category',
          label: 'Welding projects',
          collapsed: true,
          items: [
            'metalworking/welding/intro',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Leatherworking',
      collapsed: true,
      items: ['leatherworking/intro'],
    },
    {
      type: 'category',
      label: 'Cooking',
      collapsed: true,
      items: ['cooking/flatbreads'],
    },
  ],
  resourcesSidebar: [{type: 'autogenerated', dirName: 'resources'}],
};

export default sidebars;
