import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  projectsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Metalworking',
      collapsed: false,
      items: ['Metalworking/welding'],
    },
    {
      type: 'category',
      label: 'Leatherworking',
      collapsed: false,
      items: ['Leatherworking/adventure'],
    },
    {
      type: 'category',
      label: 'Cooking',
      collapsed: false,
      items: ['cooking/flatbreads'],
    },
  ],
  resourcesSidebar: [{type: 'autogenerated', dirName: 'Resources'}],
};

export default sidebars;
